# Generated by Django 3.2.4 on 2021-06-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
